Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -15,13 +15,18 @@ jobs:
           cache: gradle
 
       - name: Grant execute permission for gradlew
-        run: chmod +x gradlew
+        run: |
+          if [ -f "./gradlew" ]; then chmod +x ./gradlew; fi
+          if [ -f "./android/gradlew" ]; then chmod +x ./android/gradlew; fi
 
       - name: Build with Gradle
-        run: ./gradlew assembleDebug
+        run: |
+          if [ -f "./gradlew" ]; then ./gradlew assembleDebug;
+          elif [ -f "./android/gradlew" ]; then cd android && ./gradlew assembleDebug;
+          else echo "Gradlew not found"; exit 1; fi
 
-      - name: Upload APK
+      - name: Find and Upload APK
         uses: actions/upload-artifact@v4
         with:
-          name: app-debug
-          path: app/build/outputs/apk/debug/app-debug.apk
+          name: my-app-apk
+          path: "**/build/outputs/apk/debug/*.apk"
